#  rs.initiate({
#  _id: "example",
#  members: [
#    {_id: 0, host: "mongo1"},
#    {_id: 1, host: "mongo2"},
#  ]
#  })
services:
  mongo1:
    image: mongo
    command: --replSet example
    ports:
      - "27017:27017"
  mongo2:
    image: mongo
    command: --replSet example
    ports:
      - "27018:27017"


