services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
  mongo:
    image: mongo
    command: --replSet rs0
    ports:
      - "27017:27017"
  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"


